name: Generate requirements.txt

on:
  push:
    branches: [ main ]  # Trigger on pushes to the main branch
  pull_request:
    branches: [ main ]  # Trigger on pull requests to the main branch

jobs:
  generate-requirements:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3  # Checkout the repository code
      - name: Set up Python  # Install the necessary Python version
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Replace '3.x' with your desired version
      - name: Install pipenv  # Install Pipenv
        run: pip install pipenv
      - name: Generate requirements.txt
        run: pipenv lock > requirements.txt  # Generate the file
      - name: Commit requirements.txt  # Commit the generated file
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Generate requirements.txt
          commit_user_name: GitHub Actions
          commit_user_email: pupoawe+githubactions@gmail.com
          file_pattern: requirements.txt
